version: '3.8'

services:
  tribute-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: tribute-chatbot:latest
    container_name: tribute-chatbot
    restart: unless-stopped
    
    # Переменные окружения
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PORT=${PORT:-8080}
    
    # Монтирование конфигурационного файла (опционально)
    volumes:
      - ./config.env:/app/config.env:ro
      - ./logs:/app/logs
    
    # Порт (если понадобится в будущем)
    ports:
      - "8080:8080"
    
    # Проверка здоровья
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "tribute-chatbot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Лимиты ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Сеть
    networks:
      - tribute-network

  # Дополнительный сервис для мониторинга (опционально)
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: tribute-prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   networks:
  #     - tribute-network
  #   depends_on:
  #     - tribute-chatbot

networks:
  tribute-network:
    driver: bridge
    name: tribute-network

volumes:
  logs:
    driver: local 